version: "3"

services:
    webserver:
        build:
            context: './nginx'
            dockerfile: Dockerfile
        network: host
        ports:
            - 80:80
    hbase:
        build:
            context: './hbase'
            dockerfile: Dockerfile
        image: harisekhon/hbase
        network: host
        ports:
            - 2181:2181
        depends_on:
            - webserver
    
    mysql:
        image: mysql:5.7
        network: host
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 443502355
            MYSQL_DATABASE: myplant
        depends_on:
            - webserver
        restart: always
